<?php
/**
 * translated plugin for Craft CMS 3.x
 *
 * Request translations via translated from the comfort of your dashboard
 *
 * @link      https://scaramanga.agency
 * @copyright Copyright (c) 2021 Scaramanga Agency
 */

/**
 * @author    Scaramanga Agency
 * @package   Translated
 * @since     1.0.0
 */
return [
    'Translated' => 'Translated',
    'Translate' => 'Translate',
    'translated plugin loaded' => 'translated plugin loaded',
    'Settings' => 'Settings',
    'View orders' => 'View orders',
    'Orders' => 'Orders',
    'Order' => 'Order',
    'Request quotes' => 'Request quotes',
    'Authorise quotes' => 'Authorise quotes',
    'Sync data' => 'Sync data',
    'Failed to get quote to duplicate' => 'Failed to get quote to duplicate',
    'Sorry, there appears to be an issue with the translated API' =>
        'Sorry, there appears to be an issue with the translated API',
    'Failed to get get content from this entry' => 'Failed to get get content from this entry',
    'Could not save quote' => 'Could not save quote',
    'Failed to authorise order' => 'Failed to authorise order',
    'Quote converted to order' => 'Quote converted to order',
    'Failed to refresh quote' => 'Failed to refresh quote',
    'Quote successfully refreshed' => 'Quote successfully refreshed',
    'Failed to reject quote' => 'Failed to reject quote',
    'Quote successfully rejected' => 'Quote successfully rejected',
    'An order does not exist with that ID' => 'An order does not exist with that ID',
    'Pending' => 'Pending',
    'Expired' => 'Expired',
    'Processing' => 'Processing',
    'Delivered' => 'Delivered',
    'Rejected' => 'Rejected',
    'Professional' => 'Professional',
    'Premium' => 'Premium',
    'Economy' => 'Economy',
    'Failed to download autogenerated file' => 'Failed to download autogenerated file',
    'Failed to get delivery file' => 'Failed to get delivery file',
    'Failed to sync data to entry' => 'Failed to sync data to entry',
    'Translated data synced to entry' => 'Translated data synced to entry',
    "Couldn't save plugin settings" => "Couldn't save plugin settings",
    'Plugin settings saved' => 'Plugin settings saved',
    'Delete' => 'Delete',
    'Please either upload an asset or supply text to be translated.' =>
        'Please either upload an asset or supply text to be translated.',
    'All Orders' => 'All Orders',
    'Are you sure you want to permanently delete the selected orders?' =>
        'Are you sure you want to permanently delete the selected orders?',
    'Orders deleted.' => 'Orders deleted.',
    'Title' => 'Title',
    'Requested on' => 'Requested on',
    'Status' => 'Status',
    'Quote total' => 'Quote total',
    'Source language' => 'Source language',
    'Target language' => 'Target language',
    'Delivery date' => 'Delivery date',
    'Requested by' => 'Requested by',
    'Reviewed by' => 'Reviewed by',
    'Approved on' => 'Approved on',
    'Rejected on' => 'Rejected on',
    'Fulfilled on' => 'Fulfilled on',
    'Could not find order record' => 'Could not find order record',
    'Please select...' => 'Please select...',
    'Failed to get a response from the translated API. Try again later.' =>
        'Failed to get a response from the translated API. Try again later.',
    'Failed to upload the asset automatically. Download the file and attach it manually below.' =>
        'Failed to upload the asset automatically. Download the file and attach it manually below.',
    'Download file' => 'Download file',
    'This will be automatically generated from the entry title, but you can modify it or create your own.' =>
        'This will be automatically generated from the entry title, but you can modify it or create your own.',
    'Economy – Machine Translation with light human review.' =>
        'Economy – Machine Translation with light human review.',
    'Premium – Human Translation with quality control.' => 'Premium – Human Translation with quality control.',
    'Professional – Human Translation with specialist review and quality control.' =>
        'Professional – Human Translation with specialist review and quality control.',
    'Please identify the language of the text to be translated.' =>
        'Please identify the language of the text to be translated.',
    'Please identify the language that you want to be supplied.' =>
        'Please identify the language that you want to be supplied.',
    'Select a category that best describes the subject matter of your text to help allocate this to the most appropriate translator.' =>
        'Select a category that best describes the subject matter of your text to help allocate this to the most appropriate translator.',
    'This will be automatically generated from the submitted entry, however, if you are uploading your own document then you will need to provide this information.' =>
        'This will be automatically generated from the submitted entry, however, if you are uploading your own document then you will need to provide this information.',
    'Provide additional notes to the translator' => 'Provide additional notes to the translator',
    'You can either add your text directly to this text field or upload a document' =>
        'You can either add your text directly to this text field or upload a document',
    'Accepted formats include: CSV, Word and Text. Your translation will be returned in the same format.' =>
        'Accepted formats include: CSV, Word and Text. Your translation will be returned in the same format.',
    'Failed to sync content automatically. There may be an issue with the supplied file. Contact your project manager' =>
        'Failed to sync content automatically. There may be an issue with the supplied file. Contact your project manager',
    'Original Entry' => 'Original Entry',
    'Select which site to push the translated content to' => 'Select which site to push the translated content to',
    'Sync Content' => 'Sync Content',
    'Duplicate Quote' => 'Duplicate Quote',
    'Reject Quote' => 'Reject Quote',
    'Approve Quote' => 'Approve Quote',
    'Refresh Quote' => 'Refresh Quote',
    'Delivery' => 'Delivery',
    'Order Information' => 'Order Information',
    'Failed to get the status of this order. Please try again later.' =>
        'Failed to get the status of this order. Please try again later.',
    'Your order is still being processed. Please check back again after the delivery date has passed.' =>
        'Your order is still being processed. Please check back again after the delivery date has passed.',
    'Your order has been completed.' => 'Your order has been completed.',
    'If there are any issues when you download your file, contact your project manager' =>
        'If there are any issues when you download your file, contact your project manager',
    'Translated Content' => 'Translated Content',
    'Download Content' => 'Download Content',
    'Sync to Entry' => 'Sync to Entry',
    'Project Name' => 'Project Name',
    'Translation Level' => 'Translation Level',
    'Genre' => 'Genre',
    'Word Count' => 'Word Count',
    'Notes' => 'Notes',
    'Content' => 'Content',
    'Select file to translate' => 'Select file to translate',
    'View uploaded file' => 'View uploaded file',
    'Sandbox mode is enabled' => 'Sandbox mode is enabled',
    'Total' => 'Total',
    'Delivered on' => 'Delivered on',
    'Place new order' => 'Place new order',
    'Settings' => 'Settings',
    'Notifications' => 'Notifications',
    'Translated username' => 'Translated username',
    'Translated password' => 'Translated password',
    'Translate slugs' => 'Translate slugs',
    'Send slugs to be translated from autogenerated orders. Slugs will be automatically updated along with the content when the returned translation order is synced to an entry.' =>
        'Send slugs to be translated from autogenerated orders. Slugs will be automatically updated along with the content when the returned translation order is synced to an entry.',
    'Sandbox mode' => 'Sandbox mode',
    'The Sandbox mode allows developers to test the integration with the Translated service. Any files submitted with Sandbox mode enabled will not be translated and, therefore, no transaction will occur. Please note that the text supplied will not be translated, but returned in their original format. Response times will vary, between 30-120 seconds.' =>
        'The Sandbox mode allows developers to test the integration with the Translated service. Any files submitted with Sandbox mode enabled will not be translated and, therefore, no transaction will occur. Please note that the text supplied will not be translated, but returned in their original format. Response times will vary, between 30-120 seconds.',
    'Asset volume' => 'Asset volume',
    'Every time a translation is requested, the Translated plugin will generate a CSV file which will be sent to the translation service. Please select a volume to store these files.' =>
        'Every time a translation is requested, the Translated plugin will generate a CSV file which will be sent to the translation service. Please select a volume to store these files.',
    'Send notifications' => 'Send notifications',
    'Send notifications when translation files are delivered' =>
        'Send notifications when translation files are delivered',
    'Notification email(s)' => 'Notification email(s)',
    'Accepts comma seperated list for multiple notifyees' => 'Accepts comma seperated list for multiple notifyees'
];
